[2023-12-25T06:23:12.049-0300] {processor.py:161} INFO - Started process (PID=12448) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:23:12.052-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:23:12.056-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:23:12.054-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:23:12.202-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:23:12.200-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:23:12.203-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:23:12.240-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.198 seconds
[2023-12-25T06:24:10.408-0300] {processor.py:161} INFO - Started process (PID=12501) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:24:10.411-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:24:10.414-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:24:10.413-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:24:10.613-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:24:10.611-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:24:10.614-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:24:10.659-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.258 seconds
[2023-12-25T06:25:04.917-0300] {processor.py:161} INFO - Started process (PID=12588) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:25:04.919-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:25:04.920-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:25:04.920-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:25:05.059-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:25:05.056-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:25:05.061-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:25:05.094-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.181 seconds
[2023-12-25T06:26:18.572-0300] {processor.py:161} INFO - Started process (PID=12663) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:26:18.574-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:26:18.576-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:26:18.575-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:26:18.710-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:26:18.708-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:26:18.711-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:26:18.745-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.178 seconds
[2023-12-25T06:27:32.095-0300] {processor.py:161} INFO - Started process (PID=12731) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:27:32.099-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:27:32.101-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:27:32.101-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:27:32.250-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:27:32.248-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:27:32.251-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:27:32.285-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.194 seconds
[2023-12-25T06:28:24.513-0300] {processor.py:161} INFO - Started process (PID=12781) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:28:24.515-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:28:24.517-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:28:24.517-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:28:24.668-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:28:24.665-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:28:24.668-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:28:24.702-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.194 seconds
[2023-12-25T06:29:19.058-0300] {processor.py:161} INFO - Started process (PID=12829) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:29:19.061-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:29:19.063-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:29:19.062-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:29:19.224-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:29:19.221-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:29:19.225-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:29:19.267-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.216 seconds
[2023-12-25T06:30:35.418-0300] {processor.py:161} INFO - Started process (PID=12936) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:30:35.421-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:30:35.422-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:30:35.422-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:30:35.544-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:30:35.541-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:30:35.545-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:30:35.580-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.166 seconds
[2023-12-25T06:31:56.774-0300] {processor.py:161} INFO - Started process (PID=13007) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:31:56.776-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:31:56.778-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:31:56.778-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:31:56.947-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:31:56.944-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:31:56.949-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:31:56.981-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.211 seconds
[2023-12-25T06:32:50.849-0300] {processor.py:161} INFO - Started process (PID=13056) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:32:50.851-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:32:50.853-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:32:50.853-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:32:50.986-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:32:50.984-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:32:50.987-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:32:51.023-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.178 seconds
[2023-12-25T06:34:05.365-0300] {processor.py:161} INFO - Started process (PID=13125) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:34:05.367-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:34:05.369-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:34:05.369-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:34:05.497-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:34:05.495-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:34:05.498-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:34:05.535-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.174 seconds
[2023-12-25T06:35:23.723-0300] {processor.py:161} INFO - Started process (PID=13228) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:35:23.725-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:35:23.726-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:35:23.726-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:35:23.926-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:35:23.922-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:35:23.927-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:35:23.978-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.262 seconds
[2023-12-25T06:36:18.518-0300] {processor.py:161} INFO - Started process (PID=13279) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:36:18.521-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:36:18.522-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:36:18.522-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:36:18.684-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:36:18.679-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:36:18.686-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:36:18.730-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.216 seconds
[2023-12-25T06:37:16.638-0300] {processor.py:161} INFO - Started process (PID=13331) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:37:16.640-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:37:16.642-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:37:16.641-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:37:16.796-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:37:16.792-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:37:16.797-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:37:16.838-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.205 seconds
[2023-12-25T06:38:19.272-0300] {processor.py:161} INFO - Started process (PID=13384) to work on /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:38:19.275-0300] {processor.py:830} INFO - Processing file /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py for tasks to queue
[2023-12-25T06:38:19.277-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:38:19.276-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:38:19.451-0300] {logging_mixin.py:188} INFO - [2023-12-25T06:38:19.448-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py", line 138, in <module>
    branching_venv = BranchPythonVirtualenvOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 581, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2023-12-25T06:38:19.452-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py
[2023-12-25T06:38:19.492-0300] {processor.py:183} INFO - Processing /home/felipe/.local/lib/python3.10/site-packages/airflow/example_dags/example_branch_operator.py took 0.225 seconds
